# Generated by Django 5.2.6 on 2025-09-23 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transfer_value',
            field=models.IntegerField(blank=True, help_text='Трансферная стоимость в евро', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200000000)]),
        ),
    ]
