# Generated by Django 5.2.6 on 2025-09-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_transfer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
        migrations.AddField(
            model_name='player',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
