# Generated by Django 5.2.6 on 2025-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_player_name_remove_player_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fullname',
            field=models.CharField(default='nn', max_length=200),
            preserve_default=False,
        ),
    ]
