# Generated by Django 5.2.6 on 2025-09-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
